name: Full DevOps Pipeline 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 📦
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules 📦
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 🛠️
        run: npm install

      - name: Build project 📚
        run: npm run build

      - name: Test build output exists 🔍
        run: |
          if [ ! -f "build/index.html" ]; then
            echo "❌ Build failed: index.html not found!"
            exit 1
          else
            echo "✅ Build successful!"
          fi

      - name: Serve build directory 🌐
        run: |
          npm install -g http-server
          http-server ./build -p 3000 &

      - name: Lighthouse audit 🌟
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          commit_message: "🚀 Auto-deploy to GitHub Pages"

      - name: Done 🎉
        run: echo "✅ Deployment completed successfully!"

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout repository 📦
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🛠️
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub 🐳
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image 🚢
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: costadevop/my-portfolio:latest

      - name: Done 🎉
        run: echo "✅ Docker image build & push completed successfully!"
